Aligning to target
primo4586/RobotCode2023 pull request #7
Opened 2023-02-10 20:56 UTC by ori-coval

the lilArm should be double dont change that

2023-02-10 21:27 UTC, danielml2 requested changes
I feel like this whole command should just be a `ProxyCommand`.

I think it should be a function returning the command, similarly to how `followTrajectoryToTag` works.

In this case, instead of `generateTrajectoryToTag`, It would generate the trajectory to the closest alignment position. The only requirement for gripper here is to see whether we are gripping a cone or cube, which we can just pass with a BooleanSupplier, instead of depending on the subsystem.

This should pretty much be like generateTrajectoryToTag, but instead just use the given Translation2d of the cone/cube position as the goal, and also get a BooleanSupplier to decide for the cone or cube position. 
Then use the trajectory to pass to the `followTrajectory` command factory.

The logic itself is there, just the structure of the command needs to change, imo.

2023-02-10 21:27 UTC, danielml2 commented on src/main/java/frc/robot/commands/actions/AlignToTarget.java
> +public class AlignToTarget extends InstantCommand {
What is this? why are you extending instant command?

2023-02-10 21:27 UTC, danielml2 commented on src/main/java/frc/robot/commands/actions/AlignToTarget.java
> +    double AligningY;
Use lowerCamelCase for variables

2023-02-10 21:27 UTC, danielml2 commented on src/main/java/frc/robot/subsystems/Gripper.java
> +  private void putGripperInPose( double setpoint){
I guess it's fine but why is this private?

2023-02-10 21:27 UTC, danielml2 commented on src/main/java/frc/robot/commands/actions/GrabItemFromIntake.java
> +public class GrabItemFromIntake extends SequentialCommandGroup {
This is fine, but probably should've not been in this branch / PR

2023-02-10 21:27 UTC, danielml2 commented on src/main/java/frc/robot/subsystems/Gripper.java
> +  public Command gripItem(){
This is good overall, but we in the future need to make this be a RunCommand because one motor set call may not get it all the way to the setpoint.

2023-02-10 21:27 UTC, danielml2 commented on src/main/java/frc/robot/subsystems/Swerve.java
> +    public int whereToAlign(Gripper gripper){
I don't see a reason to pass the gripper here, you can just pass the boolean of "shouldWeGripCone" instead of the whole subsystem.

2023-02-10 21:27 UTC, danielml2 commented on src/main/java/frc/robot/subsystems/Swerve.java
> +                            closestXId=i;
I don't quite understand why are you using indexes of X positions, if anything you need to be using the Translation2ds of the positions on the field, rather then just deciding the closest X position, it's less error-prone and generally would be a cleaner solution in this case

2023-02-10 21:27 UTC, danielml2 commented on src/main/java/frc/robot/commands/actions/AlignToTarget.java
> +    AligningY = SwerveConstants.aligningY;
I get why aligning Y may be technically the same for each one, but I think there still would be difference a bit from cone to cube, and i'd rather use Translation2ds here, as said in the comment on the whereToAlign method.

2023-02-10 21:27 UTC, danielml2 commented on src/main/java/frc/robot/commands/actions/AlignToTarget.java
> +    swerve.followTrajectory(swerve.generateTrajectoryToGoal(alignLocation.getTranslation()),false, true );
`followTrajectory` returns a command that follows the trajectory, you can't just call it without scheduling the command

2023-02-10 21:27 UTC, danielml2 commented on src/main/java/frc/robot/commands/actions/AlignToTarget.java
> +    swerve.followTrajectory(swerve.generateTrajectoryToGoal(alignLocation.getTranslation()),false, true );
Also, look for the my overall comment on the review for how this command should look instead.

2023-02-11 12:14 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/Gripper.java
> +  public Command gripItem(){
this runOnceCommand initiates a runCommand

2023-02-11 12:18 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/Swerve.java
> +                            closestXId=i;
I did it because it was better for the earlier commit where i didnt notice there is the useAllianceColor in the followTrajectory so it made a lot of sense but the way it is right now you are correct

2023-02-11 12:19 UTC, ori-coval commented on src/main/java/frc/robot/commands/actions/AlignToTarget.java
> +    AligningY = SwerveConstants.aligningY;
cube and cones have the same y

2023-02-11 12:55 UTC, danielml2 commented on src/main/java/frc/robot/subsystems/Gripper.java
> +  public Command gripItem(){
No, it doesn't. The `runOnce` factory is as named: It's creating a command that runs _once_.

2023-02-11 12:59 UTC, danielml2 commented on src/main/java/frc/robot/subsystems/Swerve.java
> +                            closestXId=i;
Also, another thing i just thought of, you need to have different X values depending on what alliance you are.
which is another reason to just use Translation2ds of all the scoring positions, since then it's able to decide the correct goal position no matter if we're red or blue

2023-02-11 14:29 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/Swerve.java
> +                            closestXId=i;
thats what useAllianceColor does isnt it, it takes your trajectory and make it work even if you are in the diffrent alliance

2023-02-11 14:30 UTC, ori-coval commented on src/main/java/frc/robot/subsystems/Gripper.java
> +  public Command gripItem(){
yes but this specific run once command is runing turnTosetPoint command which isnt a run once command

2023-02-11 14:34 UTC, danielml2 commented on src/main/java/frc/robot/subsystems/Gripper.java
> +  public Command gripItem(){
It's not scheduling the turnToSetpoint command, the method only _returns_ the command. you can just return the turnToSetpoint command, with the setpoint changing based on what we're gripping, instead of what it is currently.

2023-02-11 14:38 UTC, danielml2 commented on src/main/java/frc/robot/subsystems/Swerve.java
> +                            closestXId=i;
Correct, but the point of useAllianceColor is for you to have the same trajectory created on the blue alliance work for both sides, it transforms the points to work on the red side. In this case, we don't want to change the trajectory's points.

Since we're following from the current position to the goal.
If you ctrl+click the source of `PathPlannerTrajectory.transformTrajectoryForAlliance()` you can see how it works and what i mean.

2023-02-11 21:01 UTC, ori-coval commented
daniel ignore the rereview i clicked by accident

2023-02-14 21:48 UTC, danielml2 approved these changes

2023-02-14 21:49 UTC, merged